import './style.css'
import { sampleActions, sampleWatches, type Action, type Watch } from './sample'
import { actionCsv } from './csv'

const app = document.querySelector<HTMLDivElement>('#app')!
let demo = location.pathname === '/demo' || new URLSearchParams(location.search).get('demo') === '1'
let watches: Watch[] = []
let actions: Action[] = []
let active = 'home'
const demoKey = 'demo:integration-changelog-watch'
const realKey = 'icw:workspace'
const licenseKey = 'sb_license:integration-changelog-watch'
const key = () => demo ? demoKey : realKey
const escape = (s:string) => s.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))

function load(){ const saved=localStorage.getItem(key()); if(saved){({watches,actions}=JSON.parse(saved)); return} if(demo){watches=structuredClone(sampleWatches);actions=structuredClone(sampleActions)} else {watches=[];actions=[]} }
function save(){ localStorage.setItem(key(),JSON.stringify({watches,actions})) }
function captureLicense(){ const u=new URL(location.href), token=u.searchParams.get('license'); if(token){localStorage.setItem(licenseKey,token);u.searchParams.delete('license');history.replaceState({},'',u.pathname+u.search+u.hash)} }
async function verifySavedLicense(){ const token=localStorage.getItem(licenseKey), checked=Number(localStorage.getItem(`${licenseKey}:checked`)||0); if(!token||Date.now()-checked<86400000)return; try{const r=await fetch(`https://api.sociobot.in/api/v1/products/integration-changelog-watch/verify?license=${encodeURIComponent(token)}`);const d=await r.json();localStorage.setItem(`${licenseKey}:checked`,String(Date.now()));localStorage.setItem(`${licenseKey}:valid`,String(!!d.valid));if(!d.valid)localStorage.removeItem(licenseKey)}catch{/* retain the optimistic saved state while offline */} }
async function hydrateReal(){ if(demo) return; try { const [w,a]=await Promise.all([fetch('/api/watches'),fetch('/api/actions')]); if(!w.ok||!a.ok) throw new Error(); watches=await w.json(); actions=await a.json(); save(); render() } catch { /* local workspace remains usable while server is unavailable */ } }
function actionCard(a:Action){ return `<article class="action ${a.acknowledged?'done':''}" data-action="${a.id}"><div class="action-top"><p class="eyebrow">Matched “${escape(a.matched)}” · ${escape(a.seenAt)}</p><span class="status">${a.acknowledged?'Acknowledged':'Needs owner'}</span></div><h3>${escape(a.title)}</h3><p>${escape(a.excerpt)}</p><dl><div><dt>Owner</dt><dd>${escape(a.owner)}</dd></div><div><dt>Check</dt><dd><code>${escape(a.command)}</code></dd></div></dl><div class="card-actions"><a href="${escape(a.url)}" target="_blank" rel="noreferrer">Open vendor notice <span class="sr-only">(opens in a new tab)</span></a>${a.acknowledged?'':`<button class="secondary ack" data-id="${a.id}">Acknowledge action</button>`}</div></article>` }
function dashboard(){
 const pending=actions.filter(a=>!a.acknowledged)
 return `<section class="dashboard" aria-labelledby="action-heading"><div class="dash-head"><div><p class="eyebrow">Your owned queue</p><h2 id="action-heading">${pending.length ? `${pending.length} action${pending.length===1?' needs':'s need'} an owner` : 'No actions need an owner'}</h2></div><div class="dash-buttons"><button id="scan" class="primary" ${watches.length?'':'disabled'}>Scan watched feeds</button><button id="add-watch" class="secondary">Add a watch</button></div></div><p id="notice" class="notice" role="status" aria-live="polite"></p><div class="dash-grid"><section><h3>Action cards</h3><div class="action-list">${actions.length ? actions.map(actionCard).join('') : `<div class="empty"><h3>No action cards yet</h3><p>Add a feed, rule, owner, and check command. Matched release notes will appear here.</p><button class="primary" id="empty-add">Add your first watch</button></div>`}</div></section><aside class="watches" aria-label="Watched feeds"><div class="side-title"><h3>Watched feeds</h3><span>${watches.length}/3 free</span></div>${watches.length?watches.map(w=>`<article class="watch"><strong>${escape(w.vendor)}</strong><span>${escape(w.owner)}</span><small>${escape(w.keywords)}</small></article>`).join(''):`<p>Nothing is watched yet.</p>`}<button id="export" class="text-button" ${actions.length?'':'disabled'}>Export action cards as CSV</button></aside></div></section>`
}
function home(){ return `<section class="hero"><div class="hero-copy"><p class="kicker">INTEGRATION CHANGELOG WATCH</p><h1 tabindex="-1">Turn vendor changes into owned actions</h1><p class="lede">For engineers who maintain payment, auth, analytics, or messaging integrations.</p><div class="hero-actions"><button class="primary" id="try-demo">Try it with sample data</button><span>See matched notices, owners, and checks.</span></div><ul class="facts"><li>Rules are written by your team.</li><li>Feeds are checked only when requested.</li><li>Three watches are free.</li></ul></div><figure><img src="/paper-cut-hero.webp" width="1536" height="1024" fetchpriority="high" decoding="async" alt="Paper release-note cards travel into a small action card."/><figcaption>Original paper-cut illustration.</figcaption></figure></section>${dashboard()}<section class="how" id="how"><p class="eyebrow">How it works</p><h2>Give each vendor change a next step</h2><ol><li><strong>Watch a public feed.</strong><span>Paste a changelog or RSS address you are allowed to read.</span></li><li><strong>Match your words.</strong><span>Use rules like “webhook”, “deprecation”, or an API version.</span></li><li><strong>Run the right check.</strong><span>Each matching notice becomes a Markdown-ready action card.</span></li></ol></section><section class="limits"><h2>What this does not do</h2><p>It does not read private portals, alter code, or detect undocumented changes.</p><p>It stores a feed hash and short excerpt, not a copied vendor archive.</p></section><section class="paid" id="pricing"><p class="eyebrow">Team tier</p><h2>More watches for $39 once</h2><p>One purchase adds hosted history, team ownership, and more than three watches.</p><a class="primary link-button" href="https://api.sociobot.in/api/v1/products/integration-changelog-watch/checkout">Buy team tier</a><form id="license-form"><label for="license">Have a license?</label><input id="license" name="license" autocomplete="off"><button class="secondary">Verify license</button><p id="license-note" role="status"></p></form></section>` }
function legal(kind:'privacy'|'terms'){ const isP=kind==='privacy'; document.title=`${isP?'Privacy':'Terms'} — Integration Changelog Watch`; return `<article class="legal"><h1 tabindex="-1">${isP?'Privacy for Integration Changelog Watch':'Terms for Integration Changelog Watch'}</h1><p>${isP?'Your watch settings and action cards are stored in your browser for the local dashboard. The server stores configured watches only when you use its API.':'Use public changelog and RSS addresses only when their terms allow it. You are responsible for your matching rules and actions.'}</p><h2>${isP?'Data handling':'Billing'}</h2><p>${isP?'No analytics or advertising scripts run here. License verification goes only to Sociobot when you choose it.':'Sociobot and Dodo are merchant of record for the optional one-time team tier. Refunds revoke the related license.'}</p><p><a href="/">Return home</a></p></article>` }
function render(){ document.title=active==='privacy'?'Privacy — Integration Changelog Watch':active==='terms'?'Terms — Integration Changelog Watch':demo?'Demo — Integration Changelog Watch':'Integration Changelog Watch — Track vendor changes'; const pageName=active==='privacy'?'Privacy':active==='terms'?'Terms':demo?'Demo':'Integration Changelog Watch'; app.innerHTML=`<a class="skip" href="#main">Skip to content</a><header><a class="wordmark" href="/" data-route="home"><span aria-hidden="true">▰</span> Changelog Watch</a><nav aria-label="Main navigation"><a href="/demo" data-route="demo">Demo</a><a href="/#how">How it works</a><a href="/privacy" data-route="privacy">Privacy</a></nav></header>${demo?`<aside class="demo-banner">Demo — sample data, nothing is saved <span><button id="reset-demo">Reset demo</button><button id="start-real">Start for real</button></span></aside>`:''}<main id="main" tabindex="-1">${active==='privacy'||active==='terms'?legal(active):home()}</main><p class="sr-only" aria-live="polite" aria-atomic="true">${pageName}</p><footer><p>Vendor notices become owned integration actions.</p><p><a href="/privacy" data-route="privacy">Privacy</a> · <a href="/terms" data-route="terms">Terms</a> · Built by Param Factory · v1</p></footer>`; bind(); }
function route(path:string, moveFocus=false){ active=path.includes('privacy')?'privacy':path.includes('terms')?'terms':'home'; demo=path==='/demo'||new URLSearchParams(location.search).get('demo')==='1'; load(); render(); if(!demo) hydrateReal(); if(moveFocus) document.querySelector<HTMLElement>('h1')?.focus({preventScroll:true}); }
function navigate(path:string){history.pushState({},'',path);route(path,true)}
async function addWatch(){ const vendor=prompt('Vendor name'); if(!vendor)return; const url=prompt('Public RSS or changelog URL'); if(!url)return; const keywords=prompt('Keywords, separated by commas','breaking,deprecation')||''; const owner=prompt('Owner','Integration owner')||''; const command=prompt('Local check command','npm test')||''; const watch={id:crypto.randomUUID(),vendor,url,keywords,owner,version:'',command}; if(!demo){try{const r=await fetch('/api/watches',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(watch)});if(!r.ok)throw new Error(await r.text()); await hydrateReal();return}catch(e){alert(`This watch was not saved to the server. ${e instanceof Error?e.message:'Try again.'}`);return}} watches.push(watch);save();render(); }
function csv(){ const out=actionCsv(actions); const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([out],{type:'text/csv'}));a.download='integration-actions.csv';a.click();URL.revokeObjectURL(a.href) }
function bind(){ document.querySelectorAll<HTMLElement>('[data-route]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();navigate((a as HTMLAnchorElement).getAttribute('href')!)})); document.querySelector('#try-demo')?.addEventListener('click',()=>navigate('/demo')); document.querySelector('#add-watch, #empty-add')?.addEventListener('click',addWatch); document.querySelector('#reset-demo')?.addEventListener('click',()=>{localStorage.removeItem(demoKey);load();render()}); document.querySelector('#start-real')?.addEventListener('click',()=>{localStorage.removeItem(demoKey);navigate('/')}); document.querySelectorAll<HTMLButtonElement>('.ack').forEach(b=>b.addEventListener('click',async()=>{const a=actions.find(x=>x.id===b.dataset.id)!;if(!demo){await fetch(`/api/actions/${a.id}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({acknowledged:true})});await hydrateReal();return}a.acknowledged=true;save();render()})); document.querySelector('#export')?.addEventListener('click',csv); document.querySelector('#scan')?.addEventListener('click',async()=>{const n=document.querySelector('#notice')!;n.textContent=navigator.onLine?'Scanning public feeds…':'You are offline. Connect, then scan again.'; if(!navigator.onLine)return; if(demo){setTimeout(()=>{n.textContent='No new matched notices were found. Your existing action cards remain.'},450);return}try{const r=await fetch('/api/scan',{method:'POST'});const d=await r.json();n.textContent=d.message;await hydrateReal()}catch{n.textContent='The scan did not finish. Check the feed address, then try again.'}}); document.querySelector<HTMLFormElement>('#license-form')?.addEventListener('submit',async e=>{e.preventDefault(); const t=(new FormData(e.currentTarget).get('license') as string).trim(); if(!t)return; localStorage.setItem('sb_license:integration-changelog-watch',t); const note=document.querySelector('#license-note')!;note.textContent='Checking your license…'; try{const r=await fetch(`https://api.sociobot.in/api/v1/products/integration-changelog-watch/verify?license=${encodeURIComponent(t)}`);const d=await r.json();note.textContent=d.valid?'Team tier is active.':'This license is not active. You can buy a new team tier.'}catch{note.textContent='Could not verify now. Your saved license will be checked later.'}}) }
window.addEventListener('popstate',()=>route(location.pathname,true)); captureLicense(); route(location.pathname); verifySavedLicense();
